services:
  app:
    build: .
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  tests:
    build: .
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    environment:
      - PYTHONPATH=/app
    command: bash -c "pip install pytest-cov && pytest tests/ -v"
    depends_on:
      - app
